core/api/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from core.api import views as core_api_views
from core.api.utils import CustomDefaultRouter

app_name = "core-api"

router = CustomDefaultRouter()
router.register(r"users", core_api_views.UserViewSet, basename="user")
router.register(
    r"institutions", core_api_views.InstitutionViewSet, basename="institution"
)

urlpatterns = [
    path("", include(router.urls)),
    path(
        "auth/login/",
        auth_views.LoginView.as_view(
            template_name="api/login.html",
        ),
        name="login",
    ),
    path(
        "user-profiles/",
        core_api_views.UserProfileListView.as_view(),
        name="user-profile-list",
    ),
    path(
        "user-profiles/<str:pk>/",
        core_api_views.UserProfileDetailView.as_view(),
        name="user-profile-detail",
    ),
    path(
        "institution-profiles/",
        core_api_views.InstitutionProfileListView.as_view(),
        name="institution-profile-list",
    ),
    path(
        "institution-profiles/<str:pk>/",
        core_api_views.InstitutionProfileDetailView.as_view(),
        name="institution-profile-detail",
    ),
]

core/urls.py
from django.urls import path

from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.home, name="home"),
]

eduverse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework.authtoken import views as token_views

from core import views as core_views

urlpatterns = [
    path("", include("core.urls")),
    path("core-admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/swagger/", SpectacularSwaggerView.as_view(), name="swagger-docs"
    ),
    path("api/docs/", SpectacularRedocView.as_view(), name="api-docs"),
    path("api/", include("core.api.urls")),
    path("api/", include("students.api.urls")),
    path("api/", include("teachers.api.urls")),
    path("api/auth/", include("rest_framework.urls")),
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "register/",
        core_views.UserRegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        core_views.UserLoginView.as_view(
            redirect_authenticated_user=True,
            template_name="core/login.html",
            authentication_form=core_views.UserLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/"),
        name="logout",
    ),
    path(
        "password_reset/",
        core_views.ResetPasswordView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="core/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="core/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password_change/",
        core_views.ChangePasswordView.as_view(),
        name="password_change",
    ),
    path("api/token/", token_views.obtain_auth_token, name="api-token"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]


urlpatterns += staticfiles_urlpatterns()

core/api/views.py
import os

import yaml
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from rest_framework import permissions, viewsets
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from core.api import utils
from core.api.permissions import (
    IsOwnerOrAdmin,
    IsPartOfInstitution,
    IsSuperAdminOrAdmin,
)
from core.api.serializers import (
    InstitutionProfileSerializer,
    InstitutionSerializer,
    UserProfileSerializer,
    UserSerializer,
)
from core.models import Institution, InstitutionProfile, User, UserProfile


def get_base_template(role):
    match role:
        case "Super Admin":
            return "core/dashboards/admin_dashboard.html"
        case "Student":
            return "students/student_dashboard.html"
        case "Teacher":
            return "teachers/teacher_dashboard.html"
        case _:
            return "core/dashboards/dashboard_base.html"


class APISchemaView(View):
    """
    A view class for retrieving the API schema.

    This view class handles the GET request and returns the API schema in YAML
    format.

    Methods:
        get(request, *args, **kwargs): Retrieves the API schema and returns it
        as a YAML response.
    """

    def get(self, request, *args, **kwargs):
        with open(os.environ.get("API_SCHEMA"), "r") as file:
            schema = yaml.safe_load(file)
        return HttpResponse(
            yaml.dump(schema), content_type="application/vnd.oai.openapi"
        )


@method_decorator(cache_page(60 * 60 * 2), name="dispatch")
class UserViewSet(viewsets.ModelViewSet):
    """
    A view class for handling User objects.

    This view class handles the CRUD operations for User objects.
    """

    serializer_class = UserSerializer
    permission_classes = [IsOwnerOrAdmin, permissions.IsAuthenticated]
    filterset_fields = [
        "username",
        "first_name",
        "last_name",
        "fullname",
        "email",
        "date_of_birth",
        "address",
        "sex",
        "phone_number",
        "role",
        "institution",
    ]
    search_fields = ["=username", "=email"]
    ordering_fields = ["username", "role"]

    def get_queryset(self):
        """
        Returns the queryset of users based on the user's authentication and
        role.

        Returns:
            queryset: The queryset of users.
        """
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser:
                return User.objects.all()

            if user.institution:
                # Return all users in the institution that the user belongs to
                return User.objects.filter(institution_id=user.institution_id)

            # for users who are not superusers and do not belong to any
            # institution return only their user object
            return User.objects.filter(pk=user.pk)

        return User.objects.none()


class InstitutionViewSet(viewsets.ModelViewSet):
    """
    A view class for handling Institution objects.

    This view class handles the CRUD operations for Institution objects.
    """

    serializer_class = InstitutionSerializer
    permission_classes = [IsSuperAdminOrAdmin]
    filterset_fields = "__all__"

    def get_queryset(self):
        """
        Returns the queryset of institutions based on the user's
        authentication and role.

        Returns:
            queryset: The queryset of institutions.
        """
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser:
                return Institution.objects.all()

            if user.institution_id:
                return Institution.objects.filter(id=user.institution_id)

        return Institution.objects.none()

    def get_serializer_context(self):
        return {"request": self.request}


class UserProfileListView(LoginRequiredMixin, APIView):
    """
    A view that returns a list of user profiles.
    """

    renderer_classes = [TemplateHTMLRenderer]
    template_name = "api/user_profile_list.html"
    permission_classes = [IsPartOfInstitution]
    serializer_class = UserProfileSerializer

    def get(self, request):
        """
        Handles GET requests and returns a list of user profiles.

        If the requesting user is a superuser, all user profiles are returned.
        Otherwise, only user profiles belonging to the requesting user's
        institution are returned.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            Response: A response containing the list of user profiles.
        """
        if request.user.is_superuser:
            queryset = UserProfile.objects.all()
        else:
            queryset = UserProfile.objects.filter(
                user__institution=request.user.institution
            )

        base_template = get_base_template(request.user.role)
        return Response(
            {
                "profiles": queryset,
                "base_dashboard_template": base_template,
                "name": "Manage Users",
            }
        )


class UserProfileDetailView(LoginRequiredMixin, APIView):
    """
    A view for displaying and updating user profiles.

    Attributes:
        renderer_classes (list): List of renderer classes for the view.
        template_name (str): Name of the template used for rendering the view.
        permission_classes (list): List of permission classes for the view.
    """

    renderer_classes = [TemplateHTMLRenderer]
    template_name = "api/user_profile_detail.html"
    permission_classes = [IsPartOfInstitution]
    serializer_class = UserProfileSerializer

    def get(self, request, pk, format=None):
        """
        Handles GET requests for retrieving a user profile.

        Args:
            request (HttpRequest): The HTTP request object.
            pk (int): The primary key of the user profile to retrieve.
            format (str, optional): The format of the response data.

        Returns:
            Response: The HTTP response containing the serialized user profile.
        """
        profile = get_object_or_404(UserProfile, pk=pk)

        base_template = get_base_template(request.user.role)

        serializer = UserProfileSerializer(
            profile, context={"request": request}
        )

        return Response(
            {
                "serializer": serializer,
                "profile": profile,
                "base_dashboard_template": base_template,
                "name": "Profile Update",
            }
        )

    def post(self, request, pk):
        """
        Handles POST requests for updating a user profile.

        Args:
            request (HttpRequest): The HTTP request object.
            pk (int): The primary key of the user profile to update.

        Returns:
            Response: The HTTP response indicating the success of the update.
        """
        profile = get_object_or_404(UserProfile, pk=pk)
        base_template = get_base_template(request.user.role)

        data = dict(request.data)
        user_data = utils.get_user_data(data)

        if not request.user.is_superuser:
            user_data["institution"] = profile.user.institution.pk
            user_data["role"] = profile.user.role

        serializer = UserProfileSerializer(
            profile,
            data=data,
            partial=True,
            context={"request": request},
        )

        user_serializer = UserSerializer(
            profile.user,
            data=user_data,
            partial=True,
            context={"request": request},
        )

        if not serializer.is_valid():
            return Response(
                {
                    "serializer": serializer,
                    "profile": profile,
                    "base_dashboard_template": base_template,
                }
            )

        if not user_serializer.is_valid():
            if request.user.role not in ["Super Admin", "Admin"]:
                messages.error(
                    request,
                    "You are not allowed to make this change. Please contact "
                    "your institution owner.",
                )
            else:
                # get the error and show it
                errors = user_serializer.errors
                messages.error(request, "An error occurred.")
                for key, value in errors.items():
                    messages.error(request, f"{key.split('_')}: {value[0]}")

            return Response(
                {
                    "serializer": serializer,
                    "profile": profile,
                    "errors": user_serializer.errors,
                    "base_dashboard_template": base_template,
                }
            )

        user_serializer.save()
        serializer.save()

        messages.success(request, "Profile updated successfully.")
        return redirect("core-api:user-profile-detail", pk=pk)


class InstitutionProfileListView(LoginRequiredMixin, APIView):
    """
    View for listing institution profiles.

    This view requires the user to be logged in and has the permission
    classes set to allow only super admins and admins to access it.

    Attributes:
        renderer_classes (list): List of renderer classes used for rendering
        the response.
        template_name (str): Name of the template used for rendering the HTML
        response.
        permission_classes (list): List of permission classes required to
        access the view.
    """

    renderer_classes = [TemplateHTMLRenderer]

core/templates/core/dashboards/admin_dashboard.html
{% extends "core/dashboards/dashboard_base.html" %}

{% block sidebar %}
  <nav id="sidebar"
       class="sidebar bg-blue-800 text-white h-full w-64 relative min-h-full">
    <div class="p-4">
      <h2 class="text-xl font-bold">{{ user.institution.name }}</h2>
      <ul class="mt-4">
        <li class="py-2 px-4 hover:bg-blue-800">
          <a href="{% url "core:home" %}">
            <i class="fa-solid fa-table-columns mr-2"></i>Dashboard</a>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800">
          <a href="{% url "core-api:user-profile-list" %}"> <i class="fa-solid fa-user mr-2"></i>Users</a>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800">
          <a href="#">
            <i class="fa-solid fa-gear mr-2"></i>General Settings</a>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800 submenu-item">
          <a href="#" onclick="toggleSubmenu(event, 'classesSubmenu')">
            <i class=""></i> Classes</a>
          <div class="subnav">
            <button class="subnavbtn">
              <i class="fa-solid fa-chalkboard-user mr-2"></i>
            </button>
            <div class="subnav-content">
              <a href="#allclasses">All Classes</a>
              <a href="#newclasses">New Classes</a>
            </div>
          </div>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800:">
          <a href="#"> <i class="fa-solid fa-book-open mr-2"></i>Subjects</a>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800 submenu-item">
          <a href="#" onclick="toggleSubmenu(event, 'studentsSubmenu')">
            <i class="fa-solid fa-school mr-2"></i>Students</a>
          <ul id="studentsSubmenu" class="submenu pl-4">
            <li class="py-2 px-4 hover:bg-blue-800">
              <a href="#">All Students</a>
            </li>
            <li class="py-2 px-4 hover:bg-blue-800">
              <a href="#">Add New Student</a>
            </li>
          </ul>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800 submenu-item">
          <a href="#" onclick="toggleSubmenu(event, 'employeesSubmenu')">
            <i class="fa-solid fa-person-chalkboard mr-2"></i>Employees</a>
          <ul id="employeesSubmenu" class="submenu pl-4">
            <li class="py-2 px-4 hover:bg-blue-800">
              <a href="#">All Employees</a>
            </li>
            <li class="py-2 px-4 hover:bg-blue-800">
              <a href="#">Add New Employee</a>
            </li>
          </ul>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800 submenu-item">
          <a href="#" onclick="toggleSubmenu(event, 'feesSubmenu')">
            <i class="fa-solid fa-coins mr-2"></i> Fees</a>
          <ul id="feesSubmenu" class="submenu pl-4">
            <li class="py-2 px-4 hover:bg-blue-800">
              <a href="#">Fee Defaulters</a>
            </li>
            <li class="py-2 px-4 hover:bg-blue-800">
              <a href="#">Fee Slip</a>
            </li>
          </ul>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800 submenu-item">
          <a href="#" onclick="toggleSubmenu(event, 'salarySubmenu')">
            <i class="fa-solid fa-wallet mr-2"></i>Salary</a>
          <ul id="salarySubmenu" class="submenu pl-4">
            <li class="py-2 px-4 hover:bg-blue-800">
              <a href="#">Salary Sheet</a>
            </li>
            <li class="py-2 px-4 hover:bg-blue-800">
              <a href="#">Salary Report</a>
            </li>
          </ul>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800">
          <a href="#">
            <i class="fa-solid fa-calendar-days mr-2"></i>Timetable</a>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800">
          <a href="#">
            <i class="fa-solid fa-envelope-open-text mr-2"></i>Exams</a>
        </li>
        <li class="py-2 px-4 hover:bg-blue-800">
          <form id="logout-form" method="post" action="{% url 'logout' %}">
            {% csrf_token %}
          </form>
          <a href="#" onclick="document.getElementById('logout-form').submit();">
            <i class="fa-solid fa-right-from-bracket mr-2"></i>Logout</a>
        </li>
      </ul>
    </div>
  </nav>
{% endblock sidebar %}

<div class="flex-1">
  {% block content %}
    <!-- Main Content -->
    <div class="p-4 ml-8 items-center">
      <h1 class="text-2xl font-bold">Welcome to the Admin Dashboard</h1>
      <!-- Your main content goes here -->
      <!-- Statistics Cards -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mt-4">
        <div class="stat-card">
          <div>Total Students This Month</div>
          <div class="text-xl font-bold">0</div>
        </div>
        <div class="stat-card">
          <div>Total Employees This Month</div>
          <div class="text-xl font-bold">0</div>
        </div>
        <div class="stat-card">
          <div>Revenue Generated This Month</div>
          <div class="text-xl font-bold">$0</div>
        </div>
        <div class="stat-card">
          <div>Total Profit This Month</div>
          <div class="text-xl font-bold">$0</div>
        </div>
      </div>

      <!-- Statistical Chart -->
      <div class="card">
        <canvas id="myChart"></canvas>
      </div>

      <!-- Daily Information -->
      <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4 mt-4">
        <div class="card">
          <div class="text-lg font-semibold">Absent Students Today</div>
          <div class="text-xl font-bold">0</div>
        </div>
        <div class="card">
          <div class="text-lg font-semibold">Present Employees Today</div>
          <div class="text-xl font-bold">0</div>
        </div>
        <div class="card">
          <div class="text-lg font-semibold">New Admissions Today</div>
          <div class="text-xl font-bold">0</div>
        </div>
      </div>

      <!-- Calendar for Events -->
      <div class="card mt-4">
        <div id="calendar"></div>
      </div>
    </div>
  </div>
{% endblock content %}

core/templates/core/dashboards/dashboard_base.html
{% load tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}
        {% if name %}{{ name }} - {{ user.institution.name }} |{% endif %}
        EduVerse
      {% endblock title %}
    </title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.11.3/main.min.css"
          rel="stylesheet" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'core/styles/main.css' %}">
    {% tailwind_css %}
    {% block extra_css %}
    {% endblock extra_css %}
  </head>
  <body class="bg-gray-100">
    <div>
      <!-- Header -->
      <header class="flex items-center justify-between p-4 bg-blue-800 text-white">
        <div class="flex items-center">
          <button class="mr-4 text-white focus:outline-none" onclick="toggleSidebar()">
            <i class="fas fa-bars text-2xl"></i>
          </button>
          <a href=" {% if user.institution %} {% url "core-api:institution-profile-detail" user.institution.profile.pk %} {% else %}# {% endif %}"
             class="flex flex-row items-center">
            {{ user.institution.name }}
            <img src="{{ user.institution.profile.logo.url }}"
                 alt="Institution Logo"
                 class="h-12 mr-4" />
          </a>

          <form class="relative ml-40">
            <input type="text"
                   placeholder="Search"
                   class="pl-8 pr-4 py-2 rounded bg-gray-700 border border-gray-600 focus:outline-none focus:bg-gray-600" />
            <svg class="absolute top-1/2 left-2 transform -translate-y-1/2 text-gray-400 h-5 w-5"
                 fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 20 20">
              <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l4.88 4.88-1.42 1.42-4.87-4.88zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
            </svg>
          </form>
        </div>
        <div class="flex items-center space-x-4">
          <div class="relative dropdown">
            <button class="flex items-center focus:outline-none">
              <img src="{{ user.profile.avatar.url }}"
                   alt="Admin"
                   class="h-10 w-10 rounded-full mr-2" />
            </button>
            <div class="dropdown-menu absolute right-0 mt-2 w-48 bg-white text-black rounded-md shadow-lg z-10 hidden">
              <a href="{% url "core-api:user-profile-detail" user.profile.pk %}"
                 class="block px-4 py-2 hover:bg-gray-200">Profile</a>
              {% if user.is_superuser or user == user.institution.owner %}
                <a href="#" class="block px-4 py-2 hover:bg-gray-200">Institution</a>
              {% endif %}
              <a href="#" class="block px-4 py-2 hover:bg-gray-200">Account Settings</a>
              <div class="border-t border-gray-200"></div>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
              </form>
              <a href="#"
                 class="block px-4 py-2 hover:bg-gray-200"
                 onclick="document.getElementById('logout-form').submit();">Log Out</a>
            </div>
          </div>
        </div>
      </header>
    </div>
    <div class="flex">
      {% block sidebar %}
        <!-- Sidebar content will be injected here -->
      {% endblock sidebar %}
      <!-- Main Content -->
      <main class="mx-8 mt-8">
        {% if messages %}
          <div class="container mx-auto">
            {% for message in messages %}<div class="alert alert-{{ message.tags }}">{{ message }}</div>{% endfor %}
          </div>
        {% endif %}
        {% block content %}
        {% endblock content %}
      </main>
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/5.11.3/main.min.js"></script>
      <script>
        function toggleSidebar() {
          document.getElementById("sidebar").classList.toggle("collapsed");
        }

        function toggleSubmenu(event, submenuId) {
          event.preventDefault();
          document.getElementById(submenuId).classList.toggle("submenu-open");
        }

        // Chart Data
        var ctx = document.getElementById("myChart").getContext("2d");
        var myChart = new Chart(ctx, {
          type: "bar",
          data: {
            labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
            datasets: [{
              label: "Expenses",
              data: [1000, 2000, 3000, 4000, 5000, 6000],
              backgroundColor: "rgba(255, 99, 132, 0.2)",
              borderColor: "rgba(255, 99, 132, 1)",
              borderWidth: 1,
            }, {
              label: "Income",
              data: [2000, 3000, 4000, 5000, 6000, 7000],
              backgroundColor: "rgba(54, 162, 235, 0.2)",
              borderColor: "rgba(54, 162, 235, 1)",
              borderWidth: 1,
            }, ],
          },
          options: {
            scales: {
              yAxes: [{
                ticks: {
                  beginAtZero: true,
                },
              }, ],
            },
          },
        });

        // FullCalendar
        document.addEventListener("DOMContentLoaded", function() {
          var calendarEl = document.getElementById("calendar");
          var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: "dayGridMonth",
            headerToolbar: {
              left: "prev,next today",
              center: "title",
              right: "dayGridMonth,timeGridWeek,timeGridDay",
            },
            events: [
              // Add your events here
              {
                title: "Event 1",
                start: "2024-06-01",
                end: "2024-06-02",
              }, {
                title: "Event 2",
                start: "2024-06-05",
                end: "2024-06-07",
              },
            ],
          });
          calendar.render();
        });
      </script>
    </div>

  </body>
</html>