core/api/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from core.api import views as core_api_views
from core.api.utils import CustomDefaultRouter

app_name = "core-api"

router = CustomDefaultRouter()
router.register(r"users", core_api_views.UserViewSet, basename="user")
router.register(
    r"institutions", core_api_views.InstitutionViewSet, basename="institution"
)

urlpatterns = [
    path("", include(router.urls)),
    path(
        "auth/login/",
        auth_views.LoginView.as_view(
            template_name="api/login.html",
        ),
        name="login",
    ),
    path(
        "user-profiles/",
        core_api_views.UserProfileListView.as_view(),
        name="user-profile-list",
    ),
    path(
        "user-profiles/<str:pk>/",
        core_api_views.UserProfileDetailView.as_view(),
        name="user-profile-detail",
    ),
    path(
        "institution-profiles/",
        core_api_views.InstitutionProfileListView.as_view(),
        name="institution-profile-list",
    ),
    path(
        "institution-profiles/<str:pk>/",
        core_api_views.InstitutionProfileDetailView.as_view(),
        name="institution-profile-detail",
    ),
]

core/urls.py
from django.urls import path

from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.home, name="home"),
]

eduverse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework.authtoken import views as token_views

from core import views as core_views

urlpatterns = [
    path("", include("core.urls")),
    path("core-admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/swagger/", SpectacularSwaggerView.as_view(), name="swagger-docs"
    ),
    path("api/docs/", SpectacularRedocView.as_view(), name="api-docs"),
    path("api/", include("core.api.urls")),
    path("api/", include("students.api.urls")),
    path("api/", include("teachers.api.urls")),
    path("api/auth/", include("rest_framework.urls")),
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "register/",
        core_views.UserRegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        core_views.UserLoginView.as_view(
            redirect_authenticated_user=True,
            template_name="core/login.html",
            authentication_form=core_views.UserLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/"),
        name="logout",
    ),
    path(
        "password_reset/",
        core_views.ResetPasswordView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="core/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="core/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password_change/",
        core_views.ChangePasswordView.as_view(),
        name="password_change",
    ),
    path("api/token/", token_views.obtain_auth_token, name="api-token"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]


urlpatterns += staticfiles_urlpatterns()

students/api/urls.py
from django.urls import include, path

from core.api.utils import CustomDefaultRouter
from students.api import views as student_views

app_name = "students"

router = CustomDefaultRouter()

router.register(r"students", student_views.StudentViewSet, basename="student")
router.register(
    r"guardians", student_views.GuardianViewSet, basename="guardian"
)

urlpatterns = [
    path("", include(router.urls)),
]

core/api/views.py
import os

import yaml
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from rest_framework import permissions, viewsets
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from core.api import utils
from core.api.permissions import (
    IsOwnerOrAdmin,
    IsPartOfInstitution,
    IsSuperAdminOrAdmin,
)
from core.api.serializers import (
    InstitutionProfileSerializer,
    InstitutionSerializer,
    UserProfileSerializer,
    UserSerializer,
)
from core.models import Institution, InstitutionProfile, User, UserProfile


def get_base_template(role):
    match role:
        case "Super Admin":
            return "core/dashboards/admin_dashboard.html"
        case "Student":
            return "students/student_dashboard.html"
        case "Teacher":
            return "teachers/teacher_dashboard.html"
        case _:
            return "core/dashboards/dashboard_base.html"


class APISchemaView(View):
    """
    A view class for retrieving the API schema.

    This view class handles the GET request and returns the API schema in YAML
    format.

    Methods:
        get(request, *args, **kwargs): Retrieves the API schema and returns it
        as a YAML response.
    """

    def get(self, request, *args, **kwargs):
        with open(os.environ.get("API_SCHEMA"), "r") as file:
            schema = yaml.safe_load(file)
        return HttpResponse(
            yaml.dump(schema), content_type="application/vnd.oai.openapi"
        )


@method_decorator(cache_page(60 * 60 * 2), name="dispatch")
class UserViewSet(viewsets.ModelViewSet):
    """
    A view class for handling User objects.

    This view class handles the CRUD operations for User objects.
    """

    serializer_class = UserSerializer
    permission_classes = [IsOwnerOrAdmin, permissions.IsAuthenticated]
    filterset_fields = [
        "username",
        "first_name",
        "last_name",
        "fullname",
        "email",
        "date_of_birth",
        "address",
        "sex",
        "phone_number",
        "role",
        "institution",
    ]
    search_fields = ["=username", "=email"]
    ordering_fields = ["username", "role"]

    def get_queryset(self):
        """
        Returns the queryset of users based on the user's authentication and
        role.

        Returns:
            queryset: The queryset of users.
        """
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser:
                return User.objects.all()

            if user.institution:
                # Return all users in the institution that the user belongs to
                return User.objects.filter(institution_id=user.institution_id)

            # for users who are not superusers and do not belong to any
            # institution return only their user object
            return User.objects.filter(pk=user.pk)

        return User.objects.none()


class InstitutionViewSet(viewsets.ModelViewSet):
    """
    A view class for handling Institution objects.

    This view class handles the CRUD operations for Institution objects.
    """

    serializer_class = InstitutionSerializer
    permission_classes = [IsSuperAdminOrAdmin]
    filterset_fields = "__all__"

    def get_queryset(self):
        """
        Returns the queryset of institutions based on the user's
        authentication and role.

        Returns:
            queryset: The queryset of institutions.
        """
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser:
                return Institution.objects.all()

            if user.institution_id:
                return Institution.objects.filter(id=user.institution_id)

        return Institution.objects.none()

    def get_serializer_context(self):
        return {"request": self.request}


class UserProfileListView(LoginRequiredMixin, APIView):
    """
    A view that returns a list of user profiles.
    """

    renderer_classes = [TemplateHTMLRenderer]
    template_name = "api/user_profile_list.html"
    permission_classes = [IsPartOfInstitution]
    serializer_class = UserProfileSerializer

    def get(self, request):
        """
        Handles GET requests and returns a list of user profiles.

        If the requesting user is a superuser, all user profiles are returned.
        Otherwise, only user profiles belonging to the requesting user's
        institution are returned.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            Response: A response containing the list of user profiles.
        """
        if request.user.is_superuser:
            queryset = UserProfile.objects.all()
        else:
            queryset = UserProfile.objects.filter(
                user__institution=request.user.institution
            )

        base_template = get_base_template(request.user.role)
        return Response(
            {
                "profiles": queryset,
                "base_dashboard_template": base_template,
                "name": "Manage Users",
            }
        )


class UserProfileDetailView(LoginRequiredMixin, APIView):
    """
    A view for displaying and updating user profiles.

    Attributes:
        renderer_classes (list): List of renderer classes for the view.
        template_name (str): Name of the template used for rendering the view.
        permission_classes (list): List of permission classes for the view.
    """

    renderer_classes = [TemplateHTMLRenderer]
    template_name = "api/user_profile_detail.html"
    permission_classes = [IsPartOfInstitution]
    serializer_class = UserProfileSerializer

    def get(self, request, pk, format=None):
        """
        Handles GET requests for retrieving a user profile.

        Args:
            request (HttpRequest): The HTTP request object.
            pk (int): The primary key of the user profile to retrieve.
            format (str, optional): The format of the response data.

        Returns:
            Response: The HTTP response containing the serialized user profile.
        """
        profile = get_object_or_404(UserProfile, pk=pk)

        base_template = get_base_template(request.user.role)

        serializer = UserProfileSerializer(
            profile, context={"request": request}
        )

        return Response(
            {
                "serializer": serializer,
                "profile": profile,
                "base_dashboard_template": base_template,
                "name": "Profile Update",
            }
        )

    def post(self, request, pk):
        """
        Handles POST requests for updating a user profile.

        Args:
            request (HttpRequest): The HTTP request object.
            pk (int): The primary key of the user profile to update.

        Returns:
            Response: The HTTP response indicating the success of the update.
        """
        profile = get_object_or_404(UserProfile, pk=pk)
        base_template = get_base_template(request.user.role)

        data = dict(request.data)
        user_data = utils.get_user_data(data)

        if not request.user.is_superuser:
            user_data["institution"] = profile.user.institution.pk
            user_data["role"] = profile.user.role

        serializer = UserProfileSerializer(
            profile,
            data=data,
            partial=True,
            context={"request": request},
        )

        user_serializer = UserSerializer(
            profile.user,
            data=user_data,
            partial=True,
            context={"request": request},
        )

        if not serializer.is_valid():
            return Response(
                {
                    "serializer": serializer,
                    "profile": profile,
                    "base_dashboard_template": base_template,
                }
            )

        if not user_serializer.is_valid():
            if request.user.role not in ["Super Admin", "Admin"]:
                messages.error(
                    request,
                    "You are not allowed to make this change. Please contact "
                    "your institution owner.",
                )
            else:
                # get the error and show it
                errors = user_serializer.errors
                messages.error(request, "An error occurred.")
                for key, value in errors.items():
                    messages.error(request, f"{key.split('_')}: {value[0]}")

            return Response(
                {
                    "serializer": serializer,
                    "profile": profile,
                    "errors": user_serializer.errors,
                    "base_dashboard_template": base_template,
                }
            )

        user_serializer.save()
        serializer.save()

        messages.success(request, "Profile updated successfully.")
        return redirect("core-api:user-profile-detail", pk=pk)


class InstitutionProfileListView(LoginRequiredMixin, APIView):
    """
    View for listing institution profiles.

    This view requires the user to be logged in and has the permission
    classes set to allow only super admins and admins to access it.

    Attributes:
        renderer_classes (list): List of renderer classes used for rendering
        the response.
        template_name (str): Name of the template used for rendering the HTML
        response.
        permission_classes (list): List of permission classes required to
        access the view.
    """

    renderer_classes = [TemplateHTMLRenderer]

students/api/views.py
from rest_framework import permissions, viewsets

from students.api.serializers import GuardianSerializer, StudentSerializer
from students.api.utils import (
    UserCreateMixin,
    UserDestroyMixin,
    UserUpdateMixin,
)
from students.models import Guardian, Student


class BaseViewSet(
    UserCreateMixin,
    UserUpdateMixin,
    UserDestroyMixin,
    viewsets.ModelViewSet,
):
    pass


class StudentViewSet(BaseViewSet):
    """
    A view class for handling Student objects.

    This view class handles the CRUD operations for Student objects.
    """

    serializer_class = StudentSerializer
    permission_classes = [permissions.IsAuthenticated]
    filterset_fields = "__all__"

    def get_queryset(self):
        """
        Returns the queryset of students based on the user's authentication
        and role.

        Returns:
            queryset: The queryset of students.
        """
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser:
                return Student.objects.all()

            if user.institution:
                return Student.objects.filter(
                    user__institution_id=user.institution.id
                )

            return Student.objects.none()

    def get_serializer_context(self):
        return {"request": self.request}


class GuardianViewSet(BaseViewSet):
    """
    A view class for handling Guardian objects.

    This view class handles the CRUD operations for Guardian objects.
    """

    serializer_class = GuardianSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        """
        Returns the queryset of guardians based on the user's role and institution.

        If the user is a superuser, it returns all Guardian objects.
        If the user is not a superuser, it returns Guardian objects with the
        same institution as the user.

        Returns:
            QuerySet: The queryset of guardians.
        """
        user = self.request.user
        if user.is_authenticated:
            if user.is_superuser:
                return Guardian.objects.all()

            if user.institution:
                return Guardian.objects.filter(
                    user__institution_id=user.institution_id,
                    user__role="Guardian",
                )

            return Guardian.objects.none()

core/api/templates/api/login.html
{% extends "rest_framework/base.html" %}
{% load static %}
{% load rest_framework %}

{% block title %}
  {% if name %}{{ name }} -{% endif %}
  EduVerse API
{% endblock title %}
{% block body %}
  <div>
    {% if messages %}
      {% for message in messages %}<div class="alert alert-{{ message.tags }}">{{ message }}</div>{% endfor %}
    {% endif %}
  </div>
  <body class="container">
    <div class="container-fluid" style="margin-top: 30px">
      <div class="row-fluid">
        <div class="well"
             style="width: 320px;
                    margin-left: auto;
                    margin-right: auto">
          <div class="row-fluid">
            <div>
              {% block branding %}

                <h3 style="margin: 0 0 20px; text-align: center">
                  <a href="{% url 'api-docs' %}">EduVerse API</a>
                </h3>

              {% endblock branding %}
            </div>
          </div>
          <div class="row-fluid">
            <div>
              <form action="{% url 'core-api:login' %}" role="form" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <div id="div_id_username"
                     class="clearfix control-group
                            {% if form.username.errors %}error{% endif %}">
                  <div class="form-group">
                    <label for="id_username">{{ form.username.label }}:</label>
                    <input type="text"
                           name="username"
                           maxlength="100"
                           autocapitalize="off"
                           autocorrect="off"
                           class="form-control textinput textInput"
                           id="id_username"
                           required
                           autofocus
                           {% if form.username.value %}value="{{ form.username.value }}"{% endif %}>
                    {% if form.username.errors %}<p class="text-error">{{ form.username.errors|striptags }}</p>{% endif %}
                  </div>
                </div>
                <div id="div_id_password"
                     class="clearfix control-group
                            {% if form.password.errors %}error{% endif %}">
                  <div class="form-group">
                    <label for="id_password">{{ form.password.label }}:</label>
                    <input type="password"
                           name="password"
                           maxlength="100"
                           autocapitalize="off"
                           autocorrect="off"
                           class="form-control textinput textInput"
                           id="id_password"
                           required>
                    {% if form.password.errors %}<p class="text-error">{{ form.password.errors|striptags }}</p>{% endif %}
                  </div>
                </div>
                {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                    <div class="well well-small text-error" style="border: none">{{ error }}</div>
                  {% endfor %}
                {% endif %}
                <div class="form-actions-no-box">
                  <input type="submit"
                         name="submit"
                         value="Log in"
                         class="btn btn-primary form-control"
                         id="submit-id-submit">
                </div>
              </form>
              <div style="margin-top: 28px">
                <a href="#">Forgot password?</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>

{% endblock body %}

core/api/templates/api/user_profile_detail.html
{% extends base_dashboard_template %}

{% load rest_framework %}

{% block content %}
  <h1 class="text-2xl">User Profile</h1>
  <form id="profileForm" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <div class="flex flex-col">{% render_form serializer %}</div>
    <input type="submit" value="Save" class="btn btn-lg btn-red">
  </form>
{% endblock content %}

core/api/templates/api/user_profile_list.html
{% extends base_dashboard_template %}

{% block content %}
  <h1 class="text-2xl">Users</h1>
  <ul>
    {% for profile in profiles %}
      {% comment %} Add good styling to this {% endcomment %}
      <li>
        <p>
          <a href="{% url "core-api:user-profile-detail" pk=profile.pk %}">{{ profile.user.fullname }} -
            {% comment %}
            Instead of Super Admin, let's say they are the owner
            of he institution
            {% endcomment %}
            {% if profile.user.role == "Super Admin" %}
              Institution Owner
            {% else %}
              {% comment %} for all other users, their roles are used {% endcomment %}
              {{ profile.user.role }}
            {% endif %}
          </a>
        </p>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}