core/api/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from core.api import views as core_api_views
from core.api.utils import CustomDefaultRouter

app_name = "core-api"

router = CustomDefaultRouter()
router.register(r"users", core_api_views.UserViewSet, basename="user")
router.register(
    r"institutions", core_api_views.InstitutionViewSet, basename="institution"
)

urlpatterns = [
    path("", include(router.urls)),
    path(
        "auth/login/",
        auth_views.LoginView.as_view(
            template_name="api/login.html",
        ),
        name="login",
    ),
    path(
        "user-profiles/",
        core_api_views.UserProfileListView.as_view(),
        name="user-profile-list",
    ),
    path(
        "user-profiles/<str:pk>/",
        core_api_views.UserProfileDetailView.as_view(),
        name="user-profile-detail",
    ),
    path(
        "institution-profiles/",
        core_api_views.InstitutionProfileListView.as_view(),
        name="institution-profile-list",
    ),
    path(
        "institution-profiles/<str:pk>/",
        core_api_views.InstitutionProfileDetailView.as_view(),
        name="institution-profile-detail",
    ),
]

core/urls.py
from django.urls import path

from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.home, name="home"),
]

eduverse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from rest_framework.authtoken import views as token_views

from core import views as core_views

urlpatterns = [
    path("", include("core.urls")),
    path("core-admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/swagger/", SpectacularSwaggerView.as_view(), name="swagger-docs"
    ),
    path("api/docs/", SpectacularRedocView.as_view(), name="api-docs"),
    path("api/", include("core.api.urls")),
    path("api/", include("students.api.urls")),
    path("api/", include("teachers.api.urls")),
    path("api/auth/", include("rest_framework.urls")),
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "register/",
        core_views.UserRegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        core_views.UserLoginView.as_view(
            redirect_authenticated_user=True,
            template_name="core/login.html",
            authentication_form=core_views.UserLoginForm,
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/"),
        name="logout",
    ),
    path(
        "password_reset/",
        core_views.ResetPasswordView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="core/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="core/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password_change/",
        core_views.ChangePasswordView.as_view(),
        name="password_change",
    ),
    path("api/token/", token_views.obtain_auth_token, name="api-token"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]


urlpatterns += staticfiles_urlpatterns()

core/models.py
#!/usr/bin/env python3

from uuid import uuid4

from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from PIL import Image

from core.validators import Validators


class User(AbstractUser):
    """
    Represents a user in the system.

    Inherits from the AbstractUser model provided by Django's authentication framework.
    """

    ROLES = [
        ("Super Admin", "Super Admin"),
        ("Admin", "Admin"),
        ("Teacher", "Teacher"),
        ("Student", "Student"),
        ("Guardian", "Guardian"),
        ("Librarian", "Librarian"),
        ("Accountant", "Accountant"),
    ]

    SEX = [("M", "Male"), ("F", "Female")]

    id = models.UUIDField(primary_key=True, unique=True, default=uuid4)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    username = models.CharField(
        max_length=20, null=False, blank=False, unique=True
    )
    first_name = models.CharField(max_length=30, null=False, blank=False)
    last_name = models.CharField(max_length=30, null=False, blank=False)
    fullname = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(unique=True, null=False, blank=False)
    date_of_birth = models.DateField(null=False, blank=False)
    address = models.CharField(max_length=255, null=True, blank=True)
    sex = models.CharField(
        max_length=10, choices=SEX, null=False, blank=False
    )
    phone_number = PhoneNumberField(null=True, blank=True, unique=True)
    role = models.CharField(
        max_length=20,
        choices=ROLES,
        default="Super Admin",
        null=False,
        blank=False,
    )
    institution = models.ForeignKey(
        "Institution", on_delete=models.CASCADE, null=True
    )

    def __str__(self) -> str:
        """
        Returns a string representation of the user.

        The string consists of the username and the role of the user.
        """
        return f"{self.username} - {self.role}"

    def save(self, *args, **kwargs):
        """
        Saves the user instance.

        Performs additional operations before saving the user, such as running
        validators, formatting the role and sex fields, and generating the
        fullname field.
        """
        Validators.run_validators(user=self)
        self.role = self.role.title()
        if self.sex:
            self.sex = self.sex.capitalize()

        self.clean()
        self.first_name = self.first_name.title()
        self.last_name = self.last_name.title()
        self.fullname = f"{self.first_name.strip()} {self.last_name.strip()}"
        self.fullname = self.fullname.title()

        # before saving, let set all the fields with empty values to None
        for field in self._meta.fields:
            if field.null and field.blank:
                if getattr(self, field.name) == "":
                    setattr(self, field.name, None)

        super().save(*args, **kwargs)

    def get_roles(self):
        """
        Returns the list of available roles.

        Each role is represented as a string.
        """
        return [role[0] for role in self.ROLES]

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "sex"]

    class Meta:
        ordering = ["id"]


class Institution(models.Model):
    """Institution model."""

    id = models.UUIDField(primary_key=True, unique=True, default=uuid4)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100, unique=True)
    address = models.CharField(max_length=100, null=False, blank=False)
    phone_number = PhoneNumberField(null=True, unique=True)
    email = models.EmailField(unique=True, null=False)
    owner = models.ForeignKey(
        "User",
        on_delete=models.CASCADE,
        related_name="owner",
        null=False,
        blank=False,
    )
    website = models.URLField(null=True, blank=True)
    tagline = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs) -> None:
        self.full_clean()
        Validators.run_validators(user=self.owner, institution=self)
        super().save(*args, **kwargs)


class BaseProfile(models.Model):
    picture_max_width = 500
    id = models.UUIDField(primary_key=True, unique=True, default=uuid4)

    def save(self, *args, **kwargs):
        """
        Overrides the save method to resize the logo image before saving.
        """
        super().save(*args, **kwargs)

        if hasattr(self, "avatar"):
            image_field = self.avatar
        elif hasattr(self, "logo"):
            image_field = self.logo
        else:
            return

        img = Image.open(image_field.path)

        if max(img.size) > self.picture_max_width:
            width, height = img.size
            if width > height:
                ratio = self.picture_max_width / width
                new_size = (self.picture_max_width, round(height * ratio))
            else:
                ratio = self.picture_max_width / height
                new_size = (round(width * ratio), self.picture_max_width)
            img = img.resize(new_size, Image.LANCZOS)

        img.save(image_field.path)


class UserProfile(BaseProfile):
    """
    A model representing a user profile.

    Attributes:
        user (User): The user associated with the profile.
        avatar (ImageField): The profile avatar image.
        bio (TextField): The user's biography.
    """

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="profile"
    )

    avatar = models.ImageField(
        default="default.png", upload_to="profile_images"
    )
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        """
        Returns a string representation of the profile.

        Returns:
            str: The username of the associated user.
        """
        return f"{self.user.username} - Profile"


class InstitutionProfile(BaseProfile):
    """
    A model representing an institution profile.

    Attributes:
        institution (Institution): The institution associated with the profile.
        logo (ImageField): The institution logo image.
        description (TextField): The institution description.
    """

    institution = models.OneToOneField(
        Institution, on_delete=models.CASCADE, related_name="profile"
    )

    logo = models.ImageField(
        default="default.png", upload_to="institution_images"
    )
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        """
        Returns a string representation of the profile.

        Returns:
            str: The name of the associated institution.
        """
        return f"{self.institution.name} - Profile"

core/templates/core/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'core/styles/main.css' %}">
    <link rel="shortcut icon" href="/media/favicon.ico" type="image/x-icon">
    {% block extra_js %}
    {% endblock extra_js %}

    {% block extra_css %}
    {% endblock extra_css %}
    <title>
      {% block title %}
        {% if name %}{{ name }} |{% endif %}
        EduVerse
      {% endblock title %}
    </title>
    {% tailwind_css %}
  </head>
  <body class="bg-gray-100 min-h-screen flex flex-col">
    <!-- Header Section -->
    <header class="bg-white shadow-md top-0 fixed w-full z-50">
      <div class="container mx-auto px-4 py-2 flex items-center justify-between">
        <!-- Logo and Company Name -->
        <div class="flex items-center">
          <img src="{% static 'core/images/eduverse_logo_blue.jpeg' %}"
               alt="Logo"
               class="h-10 w-10 mr-2 rounded-full">
          <span class="text-xl font-bold text-blue-900">EduVerse</span>
        </div>

        <!-- Navigation Links (hidden on mobile) -->
        <div class="hidden sm:flex space-x-6">
          <a href="{% url 'core:home' %}#"
             class="text-gray-700 hover:text-blue-500 px-6">Home</a>
          <a href="{% url 'core:home' %}#Features"
             class="text-gray-700 hover:text-blue-500 px-6">Features</a>
          <a href="{% url 'core:home' %}#Services"
             class="text-gray-700 hover:text-blue-500 px-6">Services</a>
          <a href="{% url 'core:home' %}#Testimonials"
             class="text-gray-700 hover:text-blue-500 px-6">Testimonials</a>
          <a href="{% url 'core:home' %}#contact-us"
             class="text-gray-700 hover:text-blue-500 px-6">Contact</a>
        </div>

        <!-- Sign In/Sign Up Buttons (hidden on mobile) -->
        {% if user.is_authenticated %}
          {% comment %} add what should show for authenticated users {% endcomment %}
          {% comment %} Maybe give them a link back to their dashboard {% endcomment %}
          {% if user.is_staff %}
            <a href="{% url 'admin:index' %}"
               class="text-gray-700 hover:text-blue-500 px-6">Core Administration</a>
          {% endif %}
          <div class="hidden sm:flex space-x-1">
            <a href="#" class="text-gray-700 hover:text-blue-500 px-6">Dashboard</a>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
            </form>
            <a href="#"
               class="text-gray-700 hover:text-blue-500 px-6"
               onclick="document.getElementById('logout-form').submit();">Logout</a>
          {% else %}
            <div class="hidden sm:flex space-x-4">
              <a href="{% url 'register' %}"
                 class="bg-blue-500 text-white px-4 py-2 rounded">Register</a>
              <a href="{% url 'login' %}"
                 class="bg-green-500 text-white px-4 py-2 rounded">Sign In</a>
            </div>
          </div>
        {% endif %}

        <!-- Hamburger Menu (visible on mobile) -->
        <div class="sm:hidden flex items-center">
          <button id="mobile-menu-button" class="focus:outline-none">
            <svg class="w-6 h-6"
                 fill="none"
                 stroke="currentColor"
                 viewBox="0 0 24 24"
                 xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
            </svg>
          </button>
        </div>
      </div>

      <!-- Mobile Menu -->
      <div id="mobile-menu" class="hidden sm:hidden">
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
          {% if user.is_authenticated %}
            {% if user.is_staff %}
              <a href="{% url 'admin:index' %}"
                 class="block px-4 py-2 rounded-md text-base font-medium text-gray-700 hover:bg-gray-100">Core Admininstation</a>
            {% endif %}
          {% endif %}
          <a href="{% url 'core:home' %}#"
             class="block px-4 py-2 rounded-md text-base font-medium text-gray-700 hover:bg-gray-100">Home</a>
          <a href="{% url 'core:home' %}#Features"
             class="block px-4 py-2 rounded-md text-base font-medium text-gray-700 hover:bg-gray-100">Features</a>
          <a href="{% url 'core:home' %}#Services"
             class="block px-4 py-2 rounded-md text-base font-medium text-gray-700 hover:bg-gray-100">Services</a>
          <a href="{% url 'core:home' %}#Testimonials"
             class="block px-4 py-2 rounded-md text-base font-medium text-gray-700 hover:bg-gray-100">Testimonials</a>
          <a href="{% url 'core:home' %}#contact-us"
             class="block px-4 py-2 rounded-md text-base font-medium text-gray-700 hover:bg-gray-100">Contact</a>
          {% if user.is_authenticated %}
            <div class="px-3 py-2 space-y-2">
              <a href="#" class="block bg-blue-500 text-white px-2 py-2 rounded">Dashboard</a>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
              </form>
              <a href="#"
                 class="block px-4 py-2 rounded-md text-base font-medium text-gray-700 hover:bg-gray-100"
                 onclick="document.getElementById('logout-form').submit();">Logout</a>
            {% else %}
              <div class="px-3 py-2 space-y-2">
                <a href="{% url 'register' %}"
                   class="block w-full bg-blue-500 text-white px-4 py-2 rounded">Register</a>
                <a href="{% url 'login' %}"
                   class="block w-full bg-green-500 text-white px-4 py-2 rounded">Sign In</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </header>
    {% if messages %}
      {% for message in messages %}
        <div class="mt-7 {{ message.tags }} text-center px-4 py-3 relative top-4 rounded z-50">{{ message }}</div>
      {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

    <!-- Footer -->

    <footer class="bg-white shadow-lg mt-auto w-full">
      <div class="container mx-auto px-4 py-8 grid grid-cols-1 md:grid-cols-4 gap-8">
        <!-- First Section -->
        <div>
          <img src="{% static 'core/images/eduverse_logo_blue.jpeg' %}"
               alt="EduVerse Logo"
               class="h-12 w-12 mb-4 rounded-full">
          <p class="text-gray-700 mb-4">
            EduVerse is a leading provider of school management services.
            We are dedicated to delivering top-tier services and products to our customers, ensuring excellence and satisfaction in every aspect.
          </p>
          <p class="text-gray-500 text-sm">&copy; 2024 EduVerse. All rights reserved.</p>
        </div>

        <!-- Second Section -->
        <div>
          <h2 class="text-xl text-blue-900 font-bold mb-4">EduVerse</h2>
          <nav class="flex flex-col space-y-2">
            <a href="{% url 'core:home' %}#"
               class="text-gray-700 hover:text-blue-500">Home</a>
            <a href="{% url 'core:home' %}#Features"
               class="text-gray-700 hover:text-blue-500">Features</a>
            <a href="{% url 'core:home' %}#Services"
               class="text-gray-700 hover:text-blue-500">Services</a>
            <a href="{% url 'core:home' %}#Testimonials"
               class="text-gray-700 hover:text-blue-500">Testimonials</a>
            <a href="{% url 'core:home' %}#contact-us"
               class="text-gray-700 hover:text-blue-500">Contact</a>
          </nav>
        </div>

        <!-- Third Section -->
        <div>
          <h2 class="text-xl text-blue-900 font-bold mb-4">Terms</h2>
          <nav class="flex flex-col space-y-2">
            <a href="#" class="text-gray-700 hover:text-blue-500">Terms of Service</a>
            <a href="#" class="text-gray-700 hover:text-blue-500">Privacy Policy</a>
          </nav>
        </div>

        <!--Fourth Section -->

        <div>
          <h2 class="text-xl text-blue-900 font-bold mb-4">Designed and Developed by:</h2>
          <div class="flex flex-col space-y-2">
            <div>
              <p class="text-gray-700">Maxwell Nana Forson</p>
              <div class="flex space-x-2">
                <a href="https://github.com/nanafox"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-github"></i></a>
                <a href="https://linkedin.com/in/maxwellnanaforson"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-linkedin"></i></a>
                <a href="https://twitter.com/_nanafox"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-x-twitter"></i></a>
              </div>
            </div>
            <div>
              <p class="text-gray-700">Tonui Daisy</p>
              <div class="flex space-x-2">
                <a href="https://github.com/tonuidaizy"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-github"></i></a>
                <a href="https://linkedin.com/in/tonuidaizy"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-linkedin"></i></a>
                <a href="https://twitter.com/tonuidaizy"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-x-twitter"></i></a>
              </div>
            </div>
            <div>
              <p class="text-gray-700">Agwu Emmauel</p>
              <div class="flex space-x-2">
                <a href="https://github.com/emmaagwu/"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-github"></i></a>
                <a href="https://www.linkedin.com/in/emmaagwu/"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-linkedin"></i></a>
                <a href="https://x.com/nkumagwu"
                   target="_blank"
                   class="text-blue-900 hover:text-blue-500"><i class="fab fa-x-twitter"></i></a>
              </div>
            </div>
          </div>
        </div>

      </div>
    </footer>
    <!-- This script tag includes the main.js file from the 'core/js' directory in the static files. -->
    <script src="{% static 'core/js/main.js' %}"></script>
  </body>
</html>

core/templates/core/login.html
{% extends "core/base.html" %}

{% load static %}
{% block content %}
  <div class="mt-10 min-h-screen flex items-center justify-center bg-gray-100 py-24 px-4 sm:px-6 lg:px-8">
    <div class="max-w-5xl w-full grid grid-cols-1 md:grid-cols-2">
      <!-- Left side: Form -->
      <div class="bg-white p-8 shadow-lg rounded-lg">
        <div class="text-center">
          <img src="{% static 'core/images/eduverse_logo_blue.jpeg' %}"
               alt="Logo"
               class="mx-auto w-24 h-24 rounded-full">
          <p class="text-2xl font-bold mt-4 text-blue-900">Sign in to EduVerse</p>
        </div>
        <div class="mt-6 space-y-4">
          <button class="w-full flex items-center justify-center bg-white text-blue-900 py-2 px-4 border border-gray-300 rounded-md">
            <img src="{% static 'core/images/google_logo.png' %}"
                 alt="Google Logo"
                 class="w-6 h-6 mr-6">
            Sign in with Google
          </button>
          <button class="w-full flex items-center justify-center bg-white text-blue-900 py-2 px-4 border border-gray-300 rounded-md">
            <img src="{% static 'core/images/github_logo.jpeg' %}"
                 alt="Github Logo"
                 class="w-6 h-6 mr-6">
            Sign in with GitHub
          </button>
          <div class="flex items-center justify-between mt-6">
            <hr class="w-full border-t border-gray-300">
            <span class="px-2 text-gray-500">OR</span>
            <hr class="w-full border-t border-gray-300">
          </div>
          {% if form.errors %}
            <div class="alert-error mt-2" role="alert">
              <div id="form_errors" class="text-sm text-center">
                {% for key, value in form.errors.items %}<strong>{{ value }}</strong>{% endfor %}
              </div>
            </div>
          {% endif %}
          <form class="space-y-4" method="post">
            {% csrf_token %}
            <div>
              <label class="block text-sm font-medium text-blue-900">
                Email
                address
              </label>
              {{ form.email }}
              {% if form.email.errors %}<p class="text-red-500 text-sm alert-error">{{ form.email.errors.0 }}</p>{% endif %}
            </div>
            <div>
              <label class="block text-sm font-medium text-blue-900">Password</label>
              <div class="relative">
                {{ form.password }}
                {% if form.password.errors %}<p class="text-red-500 text-sm">{{ form.password.errors.0 }}</p>{% endif %}
                <span class="absolute right-3 top-1/2 transform -translate-y-1/2 cursor-pointer"
                      id="togglePassword">
                  <i class="fas fa-eye"></i>
                </span>
              </div>
            </div>
            <div class="flex items-center justify-between">
              <label class="inline-flex items-center text-blue-900">
                <input type="checkbox" name="remember_me" class="form-checkbox">
                <span class="ml-2 text-sm">Remember me</span>
              </label>
              <a href="{% url 'password_reset' %}"
                 class="text-sm text-blue-500 underline">Forgot password?</a>
            </div>
            <div>
              <button type="submit"
                      class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md">
                Sign in
              </button>
            </div>
          </form>
          <p class="text-center text-sm mt-4">
            Don't have an account yet? <a href="{% url 'register' %}" class="text-blue-500 underline">Register an account today!</a>
          </p>
        </div>
      </div>
      <!-- Right side: Image -->
      <div class="hidden md:block w-full h-full">
        <img src="{% static 'core/images/login2.png' %}"
             alt="Login Image"
             class="w-full h-full object-center rounded-lg shadow-lg">
      </div>
    </div>
  </div>
{% endblock content %}

core/templates/core/password_reset.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
  <div class="flex justify-center items-center min-h-screen bg-cover"
       style="background-image: url('{% static 'core/images/forgot_password_bg.jpg' %}')">
    <div class="w-full max-w-md">
      <div class="bg-white shadow-lg rounded-lg mt-0 mb-3">
        <div class="p-6">
          <h3 class="text-center text-2xl font-light mb-4 text-blue-900">Forgot Password?</h3>
          <p class="text-red-700 text-center mb-4">
            Enter the email address associated with your account and we will send you a link to reset your password
          </p>
          <div id="error_div"></div>
          {% if form.errors %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4"
                 role="alert">
              <strong class="font-bold">Error:</strong>
              <span class="block sm:inline">
                <div id="form_errors">
                  {% for key, value in form.errors.items %}<strong>{{ value }}</strong>{% endfor %}
                </div>
              </span>
              <button type="button"
                      class="absolute top-0 bottom-0 right-0 px-4 py-3"
                      data-dismiss="alert"
                      aria-label="Close">
                <span class="text-2xl">&times;</span>
              </button>
            </div>
          {% endif %}
          <form method="POST">
            {% csrf_token %}
            <div class="mb-4">
              <label class="block text-sm font-medium mb-2 text-blue-900" for="id_email">Email</label>
              <input type="email"
                     name="email"
                     class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                     autocomplete="email"
                     maxlength="254"
                     required
                     id="id_email"
                     placeholder="Enter email">
            </div>
            <div>
              <button type="submit"
                      class="w-full bg-blue-700 text-white py-2 rounded-md hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Submit
              </button>
            </div>
          </form>
        </div>
        <div class="p-6 text-center">
          <a href="{% url 'register' %}"
             class="text-indigo-600 hover:text-indigo-900">Create A New Account</a>
          <br>
          <br>
          <a href="{% url 'login' %}"
             class="text-indigo-600 hover:text-indigo-900">Back To Login</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

core/templates/core/password_reset_complete.html
{% extends "core/base.html" %}

{% block content %}
  <div class="container my-20 p-3">
    <div class="row justify-content-center">
      <div class="col-lg-5">
        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
          <div class="alert alert-info">
            Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

core/templates/core/password_reset_email.html
{% autoescape off %}
  Hello {{ user.username }}!

  Someone asked to reset your password! If this was you, click the link below:
  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead. If you didn't ask to reset your password, you can ignore this email and your password will not be changed.

  Sincerely,
  EduVerse Solutions
  Navigating Infinite Educational Possibilities…
{% endautoescape %}

core/templates/core/profile.html
{% extends "core/base.html" %}

{% block content %}
  <div class="row my-3 p-3">
    <div class="avatar-container">
      <img class="rounded-circle account-img"
           src="{{ user.profile.avatar.url }} "
           width="500px"
           height="500px"
           alt="user avatar" />
    </div>
  </div>
  {% if user_form.errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <div id="form_errors">
        {% for key, value in user_form.errors.items %}<strong>{{ value }}</strong>{% endfor %}
      </div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}
  <div class="form-content">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="col-md-4">
          <div class="form-group">
            <label class="small mb-1">Username</label>
            {{ user_form.username }}
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label class="small mb-1">Email</label>
            {{ user_form.email }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group">
            <a class="ml-2 btn btn-info" href="{% url 'password_change' %}">Change Password</a>
            <hr>
            <label class="small mb-1">Change Avatar:</label>
            {{ profile_form.avatar }}
            <label class="small mb-1">Bio:</label>
            {{ profile_form.bio }}
          </div>
        </div>
      </div>
      <div ml-0>
        <button type="submit" class="btn btn-success btn-lg">Save Changes</button>
        <button type="reset" class="btn btn-danger btn-lg">Reset</button>
      </div>
    </form>
  </div>
{% endblock content %}